// Package shellhook generates the self-contained scripts that `agentmod hook
// <shell>` prints and the user's rc file evals (IMPLEMENTATION_PLAN §7).
//
// The scripts do the per-prompt work in pure shell — an upward search for
// .agentmod/agentmod.toml — and exec the agentmod binary only on
// activation/deactivation transitions (D007), eval'ing `agentmod env` output
// (D016). They never touch HOME, never create shims, and no-op with a
// one-time warning when the binary is missing.
package shellhook

// Zsh returns the zsh hook script. It registers on precmd (a new shell that
// starts inside a project activates at its first prompt) and chpwd (cd
// transitions), per FABLE_PLAN §14. A project root whose activation failed
// (e.g. broken agentmod.toml) is remembered in _AGENTMOD_FAILED_ROOT so the
// error prints once instead of on every prompt; leaving and re-entering the
// project retries (D017).
func Zsh() string { return zshHook }

const zshHook = `# agentmod shell hook (zsh) — generated by 'agentmod hook zsh'; do not edit.
# Pure-shell project search on every prompt/cd; the agentmod binary runs only
# when the nearest project actually changes.

_agentmod_find_root() {
  emulate -L zsh
  local dir=$PWD
  while true; do
    if [[ -f $dir/.agentmod/agentmod.toml ]]; then
      print -r -- "$dir"
      return 0
    fi
    [[ $dir == / ]] && return 1
    dir=${dir:h}
  done
}

_agentmod_hook() {
  emulate -L zsh
  local root=""
  root=$(_agentmod_find_root) || root=""
  if [[ -n ${_AGENTMOD_FAILED_ROOT-} && $root != "$_AGENTMOD_FAILED_ROOT" ]]; then
    unset _AGENTMOD_FAILED_ROOT
  fi
  if [[ $root == "${AGENTMOD_PROJECT_ROOT-}" ]]; then
    return 0
  fi
  if [[ -n $root && $root == "${_AGENTMOD_FAILED_ROOT-}" ]]; then
    return 0
  fi
  if ! whence -p agentmod >/dev/null 2>&1; then
    if [[ -z ${_AGENTMOD_MISSING_WARNED-} ]]; then
      typeset -g _AGENTMOD_MISSING_WARNED=1
      print -r -u2 -- "agentmod: binary not found on PATH; shell hook is inactive"
    fi
    return 0
  fi
  if [[ -n $root ]]; then
    eval "$(command agentmod env --shell zsh --activate "$root")"
    if [[ "${AGENTMOD_PROJECT_ROOT-}" != "$root" ]]; then
      typeset -g _AGENTMOD_FAILED_ROOT="$root"
      if [[ -n ${AGENTMOD_PROJECT_ROOT-} ]]; then
        eval "$(command agentmod env --shell zsh --deactivate)"
      fi
    fi
  else
    eval "$(command agentmod env --shell zsh --deactivate)"
  fi
}

_agentmod_register() {
  emulate -L zsh
  typeset -ga precmd_functions chpwd_functions
  if (( ! ${precmd_functions[(I)_agentmod_hook]} )); then
    precmd_functions+=(_agentmod_hook)
  fi
  if (( ! ${chpwd_functions[(I)_agentmod_hook]} )); then
    chpwd_functions+=(_agentmod_hook)
  fi
}
_agentmod_register
`
